INSERT INTO category(id, name) VALUES(1, 'Pastas');
INSERT INTO category(id, name) VALUES(2, 'Bebidas');

INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Arroz blanco San Jose 500g', 1300, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Fideos Marolio 500g', 1250, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Secco Pomelo 3Lts', 1500, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Brahma 1.25Lts', 2400, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Heineken 1.25Lts', 2300, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Arroz blanco San Jose 500g', 1300, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Fideos Marolio 500g', 1250, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Secco Pomelo 3Lts', 1500, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Brahma 1.25Lts', 2400, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Heineken 1.25Lts', 2300, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Arroz blanco San Jose 500g', 1300, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Fideos Marolio 500g', 1250, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Secco Pomelo 3Lts', 1500, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Brahma 1.25Lts', 2400, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Heineken 1.25Lts', 2300, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Arroz blanco San Jose 500g', 1300, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Fideos Marolio 500g', 1250, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Secco Pomelo 3Lts', 1500, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Brahma 1.25Lts', 2400, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Heineken 1.25Lts', 2300, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Arroz blanco San Jose 500g', 1300, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Fideos Marolio 500g', 1250, 1,1);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Secco Pomelo 3Lts', 1500, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Brahma 1.25Lts', 2400, 1,2);
INSERT INTO product(img, description, price, available , category_id) VALUES('', 'Heineken 1.25Lts', 2300, 1,2);