spring:
  profiles:
    active: dev

info:
  application:
    name: springboot-api-rest-greisyGu-bussiness
    description: API REST from Maxikiosco GreisiGu
    author: Alex Lopez
    version: '0.0.1-SNAPSHOT'

springdoc:
  swagger-ui:
    path: /